[Web]
Port = 3000
BaseURL = 'http://localhost:3000'
CookieSecret = 'secret'
TemplateCache = false

[Database]
URL = "postgresql://postgres:12345@localhost/gonference?sslmode=disable"

[Custom]
LogoPath = ''
BrandName = ''
