# https://taskfile.dev

version: '2'

env:
  DEVENV_PATH: docker/gonference-devenv
  BACKOFFICE_UI_PATH: src/backoffice-ui

tasks:

  install-dependencies:
    desc: Installs all the dependencies for Go and Node.
    cmds:
      - |
        go get
        cd $BACKOFFICE_UI_PATH
        npm i

  devenv-up:
    desc: Runs the development environment.
    cmds:
      - |
        cd $DEVENV_PATH
        docker-compose up -d
    silent: true

  devenv-down:
    desc: Stops the development environment.
    cmds:
      - |
        cd $DEVENV_PATH
        docker-compose down
    silent: true

  build:
    desc: Builds gonference and generates a binary file called 'gonference' on project root folder.
    cmds:
      - go build -o ./out/gonference ./cmd/gonference
    silent: true
  
  run:
    desc: Runs gonference.
    cmds:
      - go run ./cmd/gonference/main.go
    silent: true

  backoffice-ui-build:
    desc: Builds the backoffice UI.
    dir: src/backoffice-ui
    cmds:
      - npm i && npm run build

  backoffice-ui-run:
    desc: Starts development service for the backoffice UI.
    dir: src/backoffice-ui
    cmds:
      - npm start

  ci:
    desc: Runs continuous integration procedures
    cmds:
      - |
        cd src/backoffice-ui
        npm i && npm run lint && npm run build
        cd ../..
        task build
