# https://taskfile.dev

version: '2'

env:
  DEVENV_PATH: docker/gonference-devenv
  BACKOFFICE_UI_PATH: src/backoffice-ui

tasks:

  install-dependencies:
    desc: Installs all the dependencies for Go and Node.
    cmds:
      - |
        go get -u github.com/gobuffalo/packr/v2/packr2
        go get
        cd $BACKOFFICE_UI_PATH
        npm i

  devenv-up:
    desc: Runs the development environment.
    cmds:
      - |
        cd $DEVENV_PATH
        docker-compose up -d
    silent: true

  devenv-down:
    desc: Stops the development environment.
    cmds:
      - |
        cd $DEVENV_PATH
        docker-compose down
    silent: true

  pack:
    desc: Runs packr2 in the directories which is needed to bundle static assets.
    cmds:
      - |
        cd src/http && packr2
        cd ../database && packr2
    silent: true

  pack-clean:
    desc: Cleans generated packr2 files.
    cmds:
      - |
        cd src/http && packr2 clean
        cd ../database && packr2 clean
    silent: true

  build:
    desc: Builds gonference and generates a binary file called 'gonference' on project root folder.
    cmds:
      - task pack
      - go build -o ./out/gonference ./cmd/gonference
      - task pack-clean
    silent: true
  
  run:
    desc: Runs gonference.
    cmds:
      - go run ./cmd/gonference/main.go
    silent: true

  backoffice-ui-build:
    desc: Builds the backoffice UI.
    cmds:
      - |
        cd $BACKOFFICE_UI_PATH
        npm run build

  backoffice-ui-start:
    desc: Starts development service for the backoffice UI.
    cmds:
      - |
        cd $BACKOFFICE_UI_PATH
        npm start

  ci:
    desc: Runs continuous integration procedures
    cmds:
      - |
        cd src/backoffice-ui
        npm i && npm run lint && npm run build
        cd ../..
        task build
