#!/usr/bin/env bash

export GOPROXY=direct

function install {(
  install-app
  install-front-style
  install-backoffice-ui
)}

function install-app {(
  cd ./src/app
  go mod download
  go get -u github.com/gobuffalo/packr/v2/packr2
)}

function install-front-style {(
  cd ./src/front-style
  npm install -s
)}

function install-backoffice-ui {(
  cd ./src/backoffice-ui
  npm install -s
)}

function run-app {(
  cd ./src/app/workdir
  go run ..
)}

function pack {(
  cd ./src/app/pkg/assets || exit
  packr2
)}

function unpack {(
  cd ./src/app/pkg/assets || exit
  packr2
)}

function devenv-up {(
  cd ./docker/devenv || exit
  docker-compose -p gonference-devenv up -d
)}

function devenv-down {(
  cd ./docker/devenv || exit
  docker-compose -p gonference-devenv down
)}

function build-app {(
  cd ./src/app
  go build -ldflags "-s -w" -o dist/gonference .
)}

function update-app {(
  cd ./src/app
  go get -u
)}

function help {(
  echo "Available commands:"
  for fn in $(compgen -A function); do echo "  ${fn}"; done
)}



set -e
cd "$(dirname "${BASH_SOURCE[0]}")"
[ -z "$1" ] && help && exit 0
"$1" ${@:2}
