#!/usr/bin/env bash

export GOPROXY=direct

function install {(
  app-install
  front-style-install
  backoffice-ui-install
)}

function app-install {(
  cd ./src/app
  go mod download
  go get -u github.com/gobuffalo/packr/v2/packr2
)}

function front-style-install {(
  cd ./src/front-style
  npm install -s
)}

function backoffice-ui-install {(
  cd ./src/backoffice-ui
  npm install -s
)}

function app-run {(
  cd ./src/app/workdir
  go run ..
)}

function front-style-run {(
  cd ./src/front-style
  npm start -s
)}

function backoffice-ui-run {(
  cd ./src/backoffice-ui
  npm start -s
)}

function app-pack {(
  cd ./src/app/pkg/assets || exit
  packr2
)}

function app-unpack {(
  cd ./src/app/pkg/assets || exit
  packr2
)}

function devenv-up {(
  cd ./docker/devenv || exit
  docker-compose -p gonference-devenv up -d
)}

function devenv-down {(
  cd ./docker/devenv || exit
  docker-compose -p gonference-devenv down
)}

function app-build {(
  cd ./src/app
  go build -ldflags "-s -w" -o dist/gonference .
)}

function app-update {(
  cd ./src/app
  go get -u
)}

function help {(
  echo "Available commands:"
  for fn in $(compgen -A function); do echo "  ${fn}"; done
)}



set -e
cd "$(dirname "${BASH_SOURCE[0]}")"
[ -z "$1" ] && help && exit 0
"$1" ${@:2}
