version: '2'

services:

  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gonference
      - POSTGRES_PASSWORD=12345
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
