version: '3.7'

services:

  db:
    image: postgres:11.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gonference
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 30

  gonference:
    image: gonference
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ./config.toml:/app/config.toml:ro
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      db:
        condition: service_healthy
