version: '3.7'

services:

  app:
    environment:
      DATABASE_URL: 'postgresql://postgres:12345@db/gonference?sslmode=disable'
      COOKIE_SECRET: 'secret'
    ports:
      - 0.0.0.0:3001:80
    volumes:
      - ./data/logs:/app/logs
      - ./data/uploads:/app/uploads

  db:
    image: postgres:11.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gonference
      - POSTGRES_PASSWORD=12345
    ports:
      - 127.0.0.1:5432:5432
